language: node_js
node_js:
- "stable" 
script:
- npm test
install:
- npm install
directories:
- "node_modules"
after_success:
- npm run coveralls
branches:
only:
- Integrate-Travis
- develop
webhooks:
- https://coveralls.io/webhook